# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the September milestone.  The API is based on the OpenAPI 3.0 specification.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InjuryTypeEnum(str, Enum):
    """
    A brief but descriptive label for the injury type
    """

    """
    allowed enum values
    """
    EAR_BLEED = 'Ear Bleed'
    ASTHMATIC = 'Asthmatic'
    LACERATION = 'Laceration'
    PUNCTURE = 'Puncture'
    SHRAPNEL = 'Shrapnel'
    CHEST_COLLAPSE = 'Chest Collapse'
    AMPUTATION = 'Amputation'
    BURN = 'Burn'
    ABRASION = 'Abrasion'
    BROKEN_BONE = 'Broken Bone'
    INTERNAL = 'Internal'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InjuryTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


