# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the September milestone.  The API is based on the OpenAPI 3.0 specification.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.military_branch_enum import MilitaryBranchEnum

class TestMilitaryBranchEnum(unittest.TestCase):
    """MilitaryBranchEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMilitaryBranchEnum(self):
        """Test MilitaryBranchEnum"""
        # inst = MilitaryBranchEnum()

if __name__ == '__main__':
    unittest.main()
