# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the September milestone.  The API is based on the OpenAPI 3.0 specification.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.conditions_character_vitals_inner import ConditionsCharacterVitalsInner

class TestConditionsCharacterVitalsInner(unittest.TestCase):
    """ConditionsCharacterVitalsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConditionsCharacterVitalsInner:
        """Test ConditionsCharacterVitalsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConditionsCharacterVitalsInner`
        """
        model = ConditionsCharacterVitalsInner()
        if include_optional:
            return ConditionsCharacterVitalsInner(
                character_id = '',
                vitals = openapi_client.models.vitals.Vitals(
                    conscious = True, 
                    avpu = 'ALERT', 
                    ambulatory = True, 
                    mental_status = 'AGONY', 
                    breathing = 'NORMAL', 
                    hrpmin = 0, 
                    spo2 = 0.0, )
            )
        else:
            return ConditionsCharacterVitalsInner(
        )
        """

    def testConditionsCharacterVitalsInner(self):
        """Test ConditionsCharacterVitalsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
