# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the September milestone.  The API is based on the OpenAPI 3.0 specification.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.character import Character

class TestCharacter(unittest.TestCase):
    """Character unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Character:
        """Test Character
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Character`
        """
        model = Character()
        if include_optional:
            return Character(
                id = 'Soldier_01',
                name = 'Mike',
                unstructured = '22 YO male Marine hit by an IED. Puncture wound on the left side of the neck.',
                unstructured_postassess = '22 YO male Marine hit by an IED. Puncture wound on the left side of the neck.  Burns cover about 30 of his body.',
                rapport = 0.0,
                demographics = openapi_client.models.demographics.Demographics(
                    age = 0, 
                    sex = 'M', 
                    race = '', 
                    military_disposition = 'Allied US', 
                    military_branch = 'US Army', 
                    rank = 'E-1', 
                    rank_title = 'Private (Recruit)', 
                    skills = [{"skill_type":"Combat","level":0.7},{"skill_type":"Medical","level":0.3}], 
                    role = 'Infantry', 
                    mission_importance = 'normal', ),
                injuries = [
                    openapi_client.models.injury.Injury(
                        name = 'Ear Bleed', 
                        location = 'right forearm', 
                        severity = 0.0, 
                        status = 'hidden', )
                    ],
                vitals = openapi_client.models.vitals.Vitals(
                    conscious = True, 
                    avpu = 'ALERT', 
                    ambulatory = True, 
                    mental_status = 'AGONY', 
                    breathing = 'NORMAL', 
                    hrpmin = 0, 
                    spo2 = 0.0, ),
                visited = True
            )
        else:
            return Character(
                id = 'Soldier_01',
                name = 'Mike',
                unstructured = '22 YO male Marine hit by an IED. Puncture wound on the left side of the neck.',
                demographics = openapi_client.models.demographics.Demographics(
                    age = 0, 
                    sex = 'M', 
                    race = '', 
                    military_disposition = 'Allied US', 
                    military_branch = 'US Army', 
                    rank = 'E-1', 
                    rank_title = 'Private (Recruit)', 
                    skills = [{"skill_type":"Combat","level":0.7},{"skill_type":"Medical","level":0.3}], 
                    role = 'Infantry', 
                    mission_importance = 'normal', ),
        )
        """

    def testCharacter(self):
        """Test Character"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
